import { MarketingNav, MarketingFooter, useLang } from "@/components/MarketingChrome";
import { usePageMeta } from "@/hooks/usePageMeta";
import { Scale } from "lucide-react";

const CONTENT = {
  it: {
    title: "Termini di servizio",
    updated: "Ultimo aggiornamento: 18 luglio 2026",
    intro: "Utilizzando FrameForge (sito web forgefps.dev, agent desktop e servizi collegati), accetti i seguenti termini. Se non sei d'accordo, non usare il servizio.",
    sections: [
      {
        h: "1. Cosa è FrameForge",
        p: "FrameForge è una piattaforma che offre: (a) una console web con AI Advisor per l'ottimizzazione del PC, generazione di build hardware e monitoraggio prezzi; (b) un agent desktop Windows scaricabile che esegue diagnostiche locali e applica tweak reversibili al sistema operativo, previo consenso esplicito dell'utente. Nessun comando viene eseguito da remoto: tutto avviene sul PC dell'utente con conferma manuale.",
      },
      {
        h: "2. Account & sicurezza",
        p: "Sei responsabile della sicurezza delle tue credenziali. Consigliamo di attivare la 2FA. Non ci assumiamo responsabilità per accessi non autorizzati derivanti da password deboli o condivise. Puoi cancellare l'account dalla pagina Account.",
      },
      {
        h: "3. Uso dell'agent desktop",
        p: "L'agent applica ottimizzazioni al sistema Windows solo dopo la tua approvazione esplicita. Ogni modifica è tracciata e reversibile tramite la funzione di Restore. L'esecuzione dell'agent è sotto la tua responsabilità: consigliamo di creare un punto di ripristino prima di applicare modifiche avanzate.",
      },
      {
        h: "4. Contenuti generati dall'AI",
        p: "Le risposte dell'AI Advisor sono generate da modelli di terze parti (Anthropic, OpenAI). Verifica sempre le raccomandazioni prima di applicarle. FrameForge non garantisce l'accuratezza al 100% dei consigli AI.",
      },
      {
        h: "5. Uso accettabile",
        p: "Vietato: abuso dell'infrastruttura (spam, scraping massivo), reverse engineering non autorizzato dell'exe, redistribuzione dell'agent senza consenso, uso per scopi illegali. Ci riserviamo il diritto di sospendere account che violano queste regole.",
      },
      {
        h: "6. Prezzi e abbonamenti",
        p: "Il piano Free è gratuito e senza scadenza. I piani a pagamento (quando attivi) saranno addebitati tramite Stripe secondo il ciclo scelto. Puoi cancellare in ogni momento: manterrai l'accesso fino alla scadenza del ciclo.",
      },
      {
        h: "7. Limitazione di responsabilità",
        p: "FrameForge è fornito \u00abas is\u00bb. Non siamo responsabili per perdite di dati, danni al sistema o perdite di ricavi derivanti dall'uso del servizio o dell'agent. Consigliamo backup regolari.",
      },
      {
        h: "8. Modifiche ai termini",
        p: "Possiamo aggiornare questi termini. Le modifiche significative saranno comunicate via email o banner in-app almeno 15 giorni prima dell'entrata in vigore.",
      },
      {
        h: "9. Contatti",
        p: "Per qualsiasi domanda su questi termini scrivici a forgefps.support@gmail.com o sul nostro server Discord.",
      },
    ],
  },
  en: {
    title: "Terms of service",
    updated: "Last updated: July 18, 2026",
    intro: "By using FrameForge (website forgefps.dev, desktop agent and related services), you agree to the following terms. If you disagree, do not use the service.",
    sections: [
      {
        h: "1. What FrameForge is",
        p: "FrameForge is a platform providing: (a) a web console with AI Advisor for PC optimization, hardware build generation and price tracking; (b) a downloadable Windows desktop agent that runs local diagnostics and applies reversible tweaks to the OS with explicit user consent. No commands are executed remotely: everything happens on the user's PC with manual confirmation.",
      },
      {
        h: "2. Account & security",
        p: "You are responsible for the security of your credentials. We recommend enabling 2FA. We are not liable for unauthorized access due to weak or shared passwords. You can delete your account from the Account page.",
      },
      {
        h: "3. Desktop agent usage",
        p: "The agent applies Windows optimizations only after your explicit approval. Every change is tracked and reversible via the Restore feature. Running the agent is your responsibility: we recommend creating a system restore point before applying advanced changes.",
      },
      {
        h: "4. AI-generated content",
        p: "AI Advisor responses are generated by third-party models (Anthropic, OpenAI). Always verify recommendations before applying them. FrameForge does not guarantee 100% accuracy of AI advice.",
      },
      {
        h: "5. Acceptable use",
        p: "Prohibited: infrastructure abuse (spam, mass scraping), unauthorized reverse engineering of the exe, agent redistribution without permission, use for illegal purposes. We reserve the right to suspend accounts that violate these rules.",
      },
      {
        h: "6. Pricing and subscriptions",
        p: "The Free plan is free with no expiration. Paid plans (when active) will be billed via Stripe according to the chosen cycle. You can cancel anytime: you will retain access until the end of the cycle.",
      },
      {
        h: "7. Limitation of liability",
        p: "FrameForge is provided \u00abas is\u00bb. We are not liable for data loss, system damage or revenue loss arising from the use of the service or the agent. We recommend regular backups.",
      },
      {
        h: "8. Changes to terms",
        p: "We may update these terms. Significant changes will be communicated via email or in-app banner at least 15 days before taking effect.",
      },
      {
        h: "9. Contact",
        p: "For any questions about these terms, write to forgefps.support@gmail.com or reach us on our Discord server.",
      },
    ],
  },
};

export default function Terms() {
  const lang = useLang();
  const c = CONTENT[lang];
  usePageMeta({
    title: `${c.title} · FrameForge`,
    description: c.intro,
  });
  return (
    <div className="min-h-screen bg-[#050505] text-white">
      <MarketingNav />
      <main className="max-w-3xl mx-auto px-6 pt-32 pb-20">
        <div className="inline-flex items-center gap-2 mb-4 text-[#E5FF00] text-xs font-mono uppercase tracking-widest">
          <Scale size={14} /> {lang === "en" ? "// Legal" : "// Legale"}
        </div>
        <h1 className="font-display font-black tracking-tighter text-4xl sm:text-5xl mb-3" data-testid="terms-title">
          {c.title}
        </h1>
        <div className="text-xs font-mono text-zinc-500 mb-8">{c.updated}</div>
        <p className="text-zinc-300 text-base leading-relaxed mb-10">{c.intro}</p>
        <div className="space-y-8">
          {c.sections.map((s, i) => (
            <section key={i} className="border-l-2 border-[#1A1A24] pl-5">
              <h2 className="font-display font-black tracking-tight text-lg mb-2 text-white">{s.h}</h2>
              <p className="text-zinc-400 text-sm leading-relaxed">{s.p}</p>
            </section>
          ))}
        </div>
      </main>
      <MarketingFooter />
    </div>
  );
}
